@State
def EMB():

    def upon_IMMEDIATE():
        FaceLeft()
        AddY(240000)
        IgnoreScreenfreeze(1)
        Visibility(1)
        Eff3DEffect('ef_emb_RG.DIG', 'ef_emb_RG_motion_000.mmot')
        RenderLayer(5)
    sprite('null', 10)
    ColorForTransition(4278190080)
    ColorTransition(4278190335, 10)
    sprite('null', 10)
    ColorTransition(4286625023, 10)
    sprite('null', 10)
    ColorTransition(4294967295, 10)
    sprite('null', 10)
    ColorTransition(4286625023, 10)
    sprite('null', 80)


@State
def EMB_OD():

    def upon_IMMEDIATE():
        FaceLeft()
        AddY(240000)
        IgnoreScreenfreeze(1)
        Visibility(1)
        Eff3DEffect('ef_emb_RG.DIG', 'ef_emb_RG_motion_000.mmot')
        RenderLayer(5)
    sprite('null', 8)
    ColorForTransition(4278190080)
    ColorTransition(4294967295, 10)
    sprite('null', 8)
    ColorTransition(4286625023, 10)
    sprite('null', 8)
    ColorTransition(4278223103, 10)
    sprite('null', 8)
    ColorTransition(4278223103, 10)
    sprite('null', 80)


@State
def EMB_RG_AH():

    def upon_IMMEDIATE():
        FaceLeft()
        AddY(240000)
        IgnoreScreenfreeze(1)
        Eff3DEffect('ef_emb_RG.DIG', 'ef_emb_RG_motion_000.mmot')
        RenderLayer(5)
    sprite('null', 10)
    ColorForTransition(4278190080)
    ColorTransition(4294901760, 10)
    sprite('null', 10)
    ColorTransition(4294912040, 10)
    sprite('null', 10)
    ColorTransition(4294948020, 10)
    sprite('null', 10)
    ColorTransition(4294901760, 10)
    sprite('null', 80)


@State
def ModelMagicCircle1():

    def upon_IMMEDIATE():
        Visibility(1)
        Eff3DEffect('rgef_mc.DIG', 'rgef_mc_motion_000.mmot')
        FaceSpawnLocation()
        ColorFromPaletteIndex(224)
        IgnoreScreenfreeze(1)
    sprite('null', 74)


@State
def DIST_RG():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        Size(5000)
        RandRotationAngle()
        AlphaValue(255)
        ParticleTransparency(1)
        PlayerTransparency(16000)
        Unknown3059(-40)
        SetScaleSpeed(50)
        ConstantAlphaModifier(-4)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)
    sprite('vrdist00', 3)
    DeviationX(-10000, 10000)
    DeviationY(-10000, 10000)
    RandAddScale(-500, 500)


@State
def rgef_drains():
    sprite('null', 1)
    Visibility(1)
    ParticleColorFromPalette(224, 224, 224)
    CallCustomizableParticle('rgef_draina', -1)


@State
def rgef_drain():
    sprite('null', 1)
    Visibility(1)
    ParticleColorFromPalette(224, 224, 224)
    CallCustomizableParticle('rgef_drainb', -1)


@State
def ThrowMazzle():
    sprite('null', 120)
    CreateParticle('rgef_muzzle00', -1)
    CreateParticle('rgef_muzzle00', -1)


@State
def rgef431_Start():
    sprite('null', 120)
    ParticleColor(4278190080, 4278190080, 16711680)
    CallCustomizableParticle('rgef_bloodkineR', -1)
    ParticleColor(4278190080, 4278190080, 16711680)
    CallCustomizableParticle('rgef_bloodkineL', -1)
    ParticleColor(4294901760, 4294901760, 16711680)
    CallCustomizableParticle('rgef_bloodkineR2', -1)
    ParticleColor(4294901760, 4294901760, 16711680)
    CallCustomizableParticle('rgef_bloodkineL2', -1)
    CallCustomizableParticle('rgef_bkburst', -1)
    ParticleLayer(2)
    ParticleColor(4294901760, 4294901760, 16711680)
    CallCustomizableParticle('rgef_bloodkineback', -1)


@State
def rgef203atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(500)
        Size(900)
        AddX(50000)
        AlphaValue(212)
    sprite('vrrgef203atk_00', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    sprite('vrrgef203atk_01', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef203atk_02', 5)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_03', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_04', 1)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    SetZVal(-500)
    sprite('vrrgef203atk_05', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_06', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef203atk_07', 4)
    AlphaValue(212)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_08', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_09', 3)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    sprite('vrrgef203atk_10', 3)
    CreateParticle('rgef02', 0)


@State
def rgef203atkD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        Size(1100)
        AlphaValue(212)
    sprite('vrrgef203atk_00', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    sprite('vrrgef203atk_01', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef203atk_02', 5)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_03', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_04', 1)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    SetZVal(-500)
    sprite('vrrgef203atk_05', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_06', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef203atk_07', 4)
    AlphaValue(212)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_08', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_09', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    sprite('vrrgef203atk_10', 3)
    CreateParticle('rgef02', 0)


@State
def rgef213atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        AlphaValue(255)
    sprite('vrrgef213atk_00', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    sprite('vrrgef213atk_01', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    sprite('vrrgef213atk_02', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef213atk_03', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    sprite('vrrgef213atk_04', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef213atk_05', 2)
    CreateParticle('rgef03', 0)
    ConstantAlphaModifier(-10)


@State
def rgef213atkD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        Size(1200)
        AlphaValue(212)
    sprite('vrrgef213atk_00', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    sprite('vrrgef213atk_01', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    sprite('vrrgef213atk_02', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    sprite('vrrgef213atk_03', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    sprite('vrrgef213atk_04', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    sprite('vrrgef213atk_05', 2)
    CreateParticle('rgef03', 0)
    ConstantAlphaModifier(-10)


@State
def rgef233atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-100)
        AlphaValue(212)
    sprite('vrrgef233atk_00', 3)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef233atk_01', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef233atk_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef233atk_03', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef233atk_04', 2)
    E0EAEffectPosition(0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef233atk_05', 5)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateParticle('rgef03', 5)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateObject('rgef_drains', 5)
    sprite('vrrgef233atk_06', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    sprite('vrrgef233atk_07', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef233atk_08', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef233atk_09', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    ConstantAlphaModifier(-10)


@State
def rgef233atkD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-100)
        AlphaValue(212)
        Size(1200)
    sprite('vrrgef233atk_00', 3)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 0)
    AddY(-100000)
    sprite('vrrgef233atk_01', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef233atk_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef233atk_03', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef233atk_04', 2)
    E0EAEffectPosition(0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef233atk_05', 5)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateParticle('rgef03', 5)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    AddY(100000)
    sprite('vrrgef233atk_06', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 4)
    sprite('vrrgef233atk_07', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef233atk_08', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef233atk_09', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    ConstantAlphaModifier(-10)


@State
def rgef253atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AlphaValue(212)
    sprite('vrrgef253atk_00', 3)
    sprite('vrrgef253atk_01', 3)
    sprite('vrrgef253atk_02', 2)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef253atk_03', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 3)
    sprite('vrrgef253atk_04', 2)
    ConstantAlphaModifier(-10)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    sprite('vrrgef253atk_05', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)


@State
def rgef253atkD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AlphaValue(212)
    sprite('vrrgef253atk_00', 3)
    sprite('vrrgef253atk_01', 3)
    sprite('vrrgef253atk_02ex01', 2)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 4)
    sprite('vrrgef253atk_03ex01', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 3)
    sprite('vrrgef253atk_04', 2)
    ConstantAlphaModifier(-10)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    sprite('vrrgef253atk_05', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)


@State
def rgef400loop():

    def upon_IMMEDIATE():
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        EnableAfterimage(1)
        AfterimageBlendMode(4)
        AfterimageInterval(1)
        AfterimageCount(3)
        AfterimageSize_1(1000)
        AfterimageSize_2(900)
        AlphaValue(255)
        SetScaleY(1100)
        AddY(-60000)
    sprite('vrrgef400atk_02', 3)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    sprite('vrrgef400atk_03', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    label(0)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1000)
    ConstantAlphaModifier(-10)
    AddX(200000)
    AddY(-5000)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1100)
    AddY(5000)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1200)
    AddY(-10000)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1100)
    AddY(-5000)
    ConstantAlphaModifier(10)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1200)
    AddY(2000)
    sprite('vrrgef400atk_04', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    Size(1100)
    AddY(-3000)
    loopRest()
    gotoLabel(0)
    sprite('null', 20)


@State
def rgef400end():

    def upon_IMMEDIATE():
        E0EAEffectPosition(3)
        IgnorePauses(3)
        RemoveOnCallStateEnd(3)
        EnableAfterimage(1)
        AfterimageBlendMode(4)
        AfterimageCount(3)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AlphaValue(255)
        SetScaleY(1100)
        AddY(-70000)
        AddX(120000)
    sprite('vrrgef400atk_05', 2)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    ConstantAlphaModifier(-10)
    sprite('vrrgef400atk_06', 4)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    E0EAEffectPosition(0)
    sprite('vrrgef400atk_07', 4)
    CreateParticle('rgef00', 0)
    CreateParticle('rgef00', 1)
    CreateParticle('rgef00', 2)
    sprite('vrrgef400atk_08', 4)
    sprite('null', 20)


@State
def rgef400nokori():

    def upon_IMMEDIATE():
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AlphaValue(255)
    sprite('vrrgef400b_00', 5)
    ConstantAlphaModifier(-2)
    physicsXImpulse(-500)
    physicsYImpulse(-500)
    sprite('vrrgef400b_01', 2)
    sprite('vrrgef400b_02', 3)
    sprite('vrrgef400b_03', 3)
    sprite('vrrgef400b_04', 3)
    sprite('vrrgef400b_05', 3)
    sprite('vrrgef400b_06', 3)
    sprite('vrrgef400b_07', 3)
    sprite('vrrgef400b_08', 3)
    sprite('vrrgef400b_09', 3)
    sprite('null', 9)
    ConstantAlphaModifier(-6)


@State
def rgef401atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(-500)
        BlendMode_Normal()
        AlphaValue(224)
    sprite('vrrgef401atk_00', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef401atk_01', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateObject('rgef_drains', 5)
    CreateObject('rgef_drains', 6)
    sprite('vrrgef401atk_02', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef401atk_03', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateObject('rgef_drains', 5)
    CreateObject('rgef_drains', 6)
    CreateObject('rgef_drains', 7)
    CreateObject('rgef_drains', 8)
    sprite('vrrgef401atk_04', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef401atk_05', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef401atk_06', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef401atk_07', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef401atk_08', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)


@State
def rgef402atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(-500)
        AlphaValue(240)
    sprite('vrrgef402atk_00', 1)
    sprite('vrrgef402atk_01', 1)
    sprite('vrrgef402atk_02', 1)
    sprite('vrrgef402atk_03', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef402atk_04', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef402atk_05', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef402atk_06', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef402atk_07', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef402atk_08', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)


@State
def rgef406atk():

    def upon_IMMEDIATE():
        AlphaValue(255)
        ConstantAlphaModifier(-20)
    sprite('vrrgef406atk_00', 3)
    CreateParticle('rgef02', 1)
    sprite('vrrgef406atk_01', 3)
    CreateParticle('rgef02', 2)
    sprite('vrrgef406atk_02', 3)
    CreateParticle('rgef02', 1)
    sprite('vrrgef406atk_03', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef406atk_00', 3)
    CreateParticle('rgef02', 1)
    sprite('vrrgef406atk_01', 3)
    CreateParticle('rgef02', 2)
    sprite('vrrgef406atk_02', 3)
    sprite('vrrgef406atk_03', 3)


@State
def rgef406batk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(-500)
        AddY(300000)
        AddX(120000)
        BlendMode_Normal()
        AlphaValue(224)
    sprite('vrrgef406batk_00', 4)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef406batk_01', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef406batk_02', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateParticle('rgef03', 5)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    CreateObject('rgef_drains', 5)
    sprite('vrrgef406batk_03', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef406batk_04', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    sprite('vrrgef406batk_05', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    ConstantAlphaModifier(-20)


@State
def rgef406batkD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        AddY(300000)
        AddX(120000)
        BlendMode_Normal()
        AlphaValue(224)
    sprite('vrrgef406batk_00', 4)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 0)
    sprite('vrrgef406batk_01', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef406batk_02', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    sprite('vrrgef406batk_03', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    sprite('vrrgef406batk_04', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    sprite('vrrgef406batk_05', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 0)
    ConstantAlphaModifier(-20)


@State
def rgef408nokori():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-500)
        AfterimageBlendMode(2)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AddX(-128000)
        AlphaValue(255)
    sprite('vrrgef408b_00', 2)
    ConstantAlphaModifier(-5)
    sprite('vrrgef408b_01', 2)
    sprite('vrrgef408b_02', 2)
    sprite('vrrgef408b_03', 2)
    sprite('vrrgef408b_04', 2)
    sprite('vrrgef408b_05', 2)
    sprite('vrrgef408b_06', 2)


@State
def rgef408Shot():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(4)
        AttackP1(90)
        Damage(1000)
        PushbackX(39900)
        AirUntechableTime(36)
        MoveAttributes(0, 0, 0, 1, 0)
        AirPushbackX(30000)
        AirPushbackY(30000)
        SameMoveProration(60)
        AirHitstunAnimation(13)
        Lifesteal(100, 100)
        ChipPercentage(0)
        GuardCrush(1, 1)
        PaletteIndex(1)
        SetZVal(-500)
        BlendMode_Normal()
        AddX(250000)
        Size(1000)

        def upon_PLAYER_DAMAGED():
            AttackOff()

        def upon_OPPONENT_HIT_OR_BLOCK():
            AttackOff()
            NoAttackDuringAction(1)
            sendToLabel(0)
    Visibility(1)
    CreateObject('408_dog', -1)
    sprite('vrrgef408_shot00', 1)
    sprite('vrrgef408_shot01', 1)
    AttackOff()
    physicsXImpulse(4000)
    Size(600)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(120)
    Size(700)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(140)
    Size(900)
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    XImpulseAcceleration(160)
    Size(1000)
    sprite('vrrgef408_shot01', 2)
    XImpulseAcceleration(180)
    sprite('vrrgef408_shot01', 4)
    XImpulseAcceleration(200)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(60)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(60)
    label(0)
    clearUponHandler(OPPONENT_HIT_OR_BLOCK)
    sprite('vrrgef408_shot02', 2)
    XImpulseAcceleration(60)
    sprite('vrrgef408_shot02', 2)
    XImpulseAcceleration(60)
    sprite('vrrgef408_shot03', 4)
    AttackOff()
    physicsXImpulse(0)
    sprite('vrrgef408_shot04', 3)
    sprite('vrrgef408_shot05', 3)
    sprite('vrrgef408_shot06', 3)
    ConstantAlphaModifier(-20)
    sprite('vrrgef408_shot07', 3)
    sprite('vrrgef408_shot06', 3)
    Visibility(1)
    sprite('vrrgef408_shot07', 3)


@State
def rgef408ShotD():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        Hitstop(6)
        AttackLevel_(4)
        AttackP1(90)
        Damage(600)
        PushbackX(23000)
        AirUntechableTime(36)
        MoveAttributes(0, 0, 0, 1, 0)
        AirPushbackX(30000)
        AirPushbackY(30000)
        SameMoveProration(60)
        SingleProration(1)
        AirHitstunAnimation(13)
        Lifesteal(100, 100)
        ChipPercentage(0)
        GuardCrush(1, 1)
        PaletteIndex(1)
        SetZVal(-500)
        BlendMode_Normal()
        AddX(250000)
        Size(1000)

        def upon_PLAYER_DAMAGED():
            AttackOff()

        def upon_OPPONENT_HIT_OR_BLOCK():
            XImpulseAcceleration(80)
            AddActionMark(1)
            if SLOT_2 == 3:
                XImpulseAcceleration(50)
                AttackOff()
                NoAttackDuringAction(1)
    Visibility(1)
    CreateObject('408_dog', -1)

    def RunOnObject_1():
        AddScale(175)
    sprite('vrrgef408_shot00', 1)
    sprite('vrrgef408_shot01', 1)
    AttackOff()
    physicsXImpulse(4000)
    Size(600)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(120)
    Size(800)
    sprite('vrrgef408_shot01', 1)
    XImpulseAcceleration(140)
    Size(1000)
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    XImpulseAcceleration(160)
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    XImpulseAcceleration(180)
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    XImpulseAcceleration(200)
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    sprite('vrrgef408_shot01', 2)
    RefreshMultihit()
    sprite('vrrgef408_shot01', 2)
    sprite('vrrgef408_shot02', 2)
    RefreshMultihit()
    sprite('vrrgef408_shot02', 2)
    RefreshMultihit()
    XImpulseAcceleration(60)
    sprite('vrrgef408_shot03', 4)
    AttackOff()
    physicsXImpulse(0)
    sprite('vrrgef408_shot04', 3)
    sprite('vrrgef408_shot05', 3)
    sprite('vrrgef408_shot06', 3)
    ConstantAlphaModifier(-20)
    sprite('vrrgef408_shot07', 3)
    sprite('vrrgef408_shot06', 3)
    Visibility(1)
    sprite('vrrgef408_shot07', 3)


@State
def __408_dog():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(4)
        Damage(900)
        AttackP1(80)
        AttackP2(82)
        SameMoveProration(60)
        AirHitstunAnimation(13)
        GroundedHitstunAnimation(13)
        AirUntechableTime(33)
        AirPushbackX(28000)
        AirPushbackY(28000)
        PushbackX(39900)
        Lifesteal(100, 100)
        ChipPercentage(0)
        StarterRating(2)

        def upon_PLAYER_DAMAGED():
            AttackOff()

        def upon_OPPONENT_HIT_OR_BLOCK():
            AttackOff()
            NoAttackDuringAction(1)
            sendToLabel(0)
        PaletteIndex(1)
        BlendMode_Normal()
        Size(800)
        AddY(8000)
        AddX(250000)
        SetZVal(-500)
        if SLOT_137:
            DamageMultiplier(80)
    sprite('vrrgef408_00', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef408_01', 1)
    physicsXImpulse(6000)
    AddScale(-500)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef408_01', 1)
    AddScale(200)
    XImpulseAcceleration(150)
    sprite('vrrgef408_01', 1)
    AddScale(200)
    XImpulseAcceleration(150)
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    XImpulseAcceleration(200)
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    AddScale(100)
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef408_02', 1)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    XImpulseAcceleration(90)
    sprite('vrrgef408_02', 1)
    XImpulseAcceleration(90)
    sprite('vrrgef408_02', 1)
    XImpulseAcceleration(90)
    label(0)
    clearUponHandler(OPPONENT_HIT_OR_BLOCK)
    sprite('vrrgef408_03', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    XImpulseAcceleration(80)
    sprite('vrrgef408_03', 2)
    XImpulseAcceleration(80)
    sprite('vrrgef408_04', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef408_04', 2)
    XImpulseAcceleration(50)
    sprite('vrrgef408_05', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    XImpulseAcceleration(50)
    sprite('vrrgef408_06', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    physicsXImpulse(0)
    sprite('vrrgef408_07', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef408_08', 4)


@State
def __408_dogD():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(4)
        Damage(900)
        AttackP1(80)
        AttackP2(82)
        SingleProration(1)
        SameMoveProration(60)
        AirHitstunAnimation(13)
        AirUntechableTime(36)
        AirPushbackX(30000)
        AirPushbackY(30000)
        PushbackX(23000)
        Hitstop(6)
        Lifesteal(50, 100)
        ChipPercentage(0)
        StarterRating(2)

        def upon_PLAYER_DAMAGED():
            AttackOff()

        def upon_OPPONENT_HIT():
            if SLOT_51:
                clearUponHandler(OPPONENT_HIT)
                Damage(300)
            SLOT_51 = 1

        def upon_OPPONENT_HIT_OR_BLOCK():
            XImpulseAcceleration(80)
            AddActionMark(1)
            if SLOT_2 == 3:
                XImpulseAcceleration(50)
                AttackOff()
                NoAttackDuringAction(1)
        PaletteIndex(1)
        BlendMode_Normal()
        Size(800)
        AddY(8000)
        AddX(250000)
        SetZVal(-500)
        if SLOT_137:
            DamageMultiplier(80)
    sprite('vrrgef408_00', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef408_01', 1)
    physicsXImpulse(8000)
    AddScale(-500)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef408_01', 1)
    AddScale(200)
    XImpulseAcceleration(150)
    sprite('vrrgef408_01', 1)
    AddScale(200)
    XImpulseAcceleration(150)
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    XImpulseAcceleration(200)
    RefreshMultihit()
    WallCollisionDetection(1)
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    AddScale(100)
    RefreshMultihit()
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    AddScale(100)
    RefreshMultihit()
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    RefreshMultihit()
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    RefreshMultihit()
    sprite('vrrgef408_02', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    RefreshMultihit()
    sprite('vrrgef408_02', 1)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    XImpulseAcceleration(90)
    sprite('vrrgef408_02', 1)
    XImpulseAcceleration(90)
    sprite('vrrgef408_02', 1)
    XImpulseAcceleration(90)
    label(0)
    clearUponHandler(OPPONENT_HIT_OR_BLOCK)
    sprite('vrrgef408_03', 2)
    WallCollisionDetection(0)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    XImpulseAcceleration(80)
    sprite('vrrgef408_03', 2)
    XImpulseAcceleration(80)
    sprite('vrrgef408_04', 2)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    sprite('vrrgef408_04', 2)
    XImpulseAcceleration(50)
    sprite('vrrgef408_05', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    XImpulseAcceleration(50)
    sprite('vrrgef408_06', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    physicsXImpulse(0)
    sprite('vrrgef408_07', 4)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    sprite('vrrgef408_08', 4)


@State
def rgef412effpos():

    def upon_IMMEDIATE():
        E0EAEffectPosition(2)
        IgnorePauses(2)
    sprite('vrrgef412effpos_00', 3)
    CreateParticle('rgef03', 0)
    CreateParticle('rgef03', 1)
    CreateParticle('rgef03', 2)
    CreateParticle('rgef03', 3)
    CreateParticle('rgef03', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateObject('rgef_drains', 3)
    CreateObject('rgef_drains', 4)
    sprite('vrrgef412effpos_00', 3)
    CreateParticle('rgef03', 5)
    CreateParticle('rgef03', 6)
    CreateParticle('rgef03', 7)
    CreateParticle('rgef03', 8)
    CreateParticle('rgef03', 9)
    CreateObject('rgef_drains', 5)
    CreateObject('rgef_drains', 6)
    CreateObject('rgef_drains', 7)
    CreateObject('rgef_drains', 8)
    CreateObject('rgef_drains', 9)
    sprite('vrrgef412effpos_00', 3)
    CreateParticle('rgef03', 10)
    CreateParticle('rgef03', 11)
    CreateParticle('rgef03', 12)
    CreateParticle('rgef03', 13)
    CreateObject('rgef_drains', 10)
    CreateObject('rgef_drains', 11)
    CreateObject('rgef_drains', 12)
    CreateObject('rgef_drains', 13)
    sprite('vrrgef412effpos_00', 3)
    CreateParticle('rgef03', 14)
    CreateParticle('rgef03', 15)
    CreateParticle('rgef03', 16)
    CreateParticle('rgef03', 17)
    CreateParticle('rgef03', 18)
    CreateParticle('rgef03', 19)
    CreateParticle('rgef03', 20)
    CreateParticle('rgef03', 21)
    CreateParticle('rgef03', 22)
    CreateParticle('rgef03', 23)
    CreateParticle('rgef03', 24)
    CreateParticle('rgef03', 25)
    CreateParticle('rgef03', 26)
    CreateObject('rgef_drains', 14)
    CreateObject('rgef_drains', 15)
    CreateObject('rgef_drains', 16)
    CreateObject('rgef_drains', 17)
    CreateObject('rgef_drains', 18)
    CreateObject('rgef_drains', 19)
    CreateObject('rgef_drains', 20)
    CreateObject('rgef_drains', 21)
    CreateObject('rgef_drains', 22)
    CreateObject('rgef_drains', 23)
    CreateObject('rgef_drains', 24)
    CreateObject('rgef_drains', 25)
    CreateObject('rgef_drains', 26)
    sprite('vrrgef412effpos_00', 3)
    CreateParticle('rgef03', 27)
    CreateParticle('rgef03', 28)
    CreateParticle('rgef03', 29)
    CreateObject('rgef_drains', 27)
    CreateObject('rgef_drains', 28)
    CreateObject('rgef_drains', 29)


@State
def rgef_414():

    def upon_IMMEDIATE():
        RemoveOnCallStateEnd(2)
        IgnorePauses(2)
        PaletteIndex(0)
        BlendMode_Normal()
        ForceBloomMaskOn(1)
        AddX(-32000)
    sprite('vrrgef414_10', 3)
    sprite('vrrgef414_11', 3)
    sprite('vrrgef414_12', 3)


@State
def rgef_414_fall():

    def upon_IMMEDIATE():
        RemoveOnCallStateEnd(2)
        E0EAEffectPosition(2)
        IgnorePauses(2)
        PaletteIndex(0)
        BlendMode_Normal()
        ForceBloomMaskOn(1)
    label(0)
    sprite('vrrgef414_01', 5)
    sprite('vrrgef414_02', 5)
    gotoLabel(0)


@State
def rgef432lock():

    def upon_IMMEDIATE():
        SetZVal(-100)
        BlendMode_Normal()
        AlphaValue(224)
    sprite('vrrgef432lock_00', 4)
    sprite('vrrgef432lock_01', 4)
    sprite('vrrgef432lock_02', 4)
    sprite('vrrgef432lock_03', 4)
    sprite('vrrgef432lock_04', 4)
    sprite('vrrgef432lock_05', 4)
    sprite('null', 1)


@State
def rgef432loop():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        LinkParticle('rgef432_drainhit')
        EnableAfterimage(1)
        AfterimageInterval(2)
        AfterimageCount(10)
        AfterimageSize_1(1000)
        AfterimageSize_2(1200)
        BlendMode_Normal()
        AlphaValue(192)
        Size(1000)
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    ConstantAlphaModifier(-15)
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')


@State
def rgef432loop_SP():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        RemoveOnCallStateEnd(3)
        IgnorePauses(3)
        EnableAfterimage(1)
        AfterimageInterval(2)
        AfterimageCount(10)
        AfterimageSize_1(1000)
        AfterimageSize_2(1200)
        BlendMode_Normal()
        AlphaValue(192)
        Size(1500)
    sprite('null', 2)
    CreateParticle('rgef432loopptc', -1)
    CreateParticle('rgef432_drainhit', -1)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    ConstantAlphaModifier(-15)
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')
    sprite('null', 2)
    CommonSE('007_swing_knife_1')


@State
def rgef440():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        PaletteIndex(1)
        IgnorePauses(2)
        AddX(500000)
        AddScale(200)
    sprite('vrrgef440_00', 6)
    ScreenShake(20000, 20000)
    sprite('vrrgef440_01', 5)
    sprite('vrrgef440_02', 4)
    sprite('vrrgef440_03', 3)
    sprite('vrrgef440_04', 3)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)
    CreateParticle('rgef02', 1)
    CreateObject('rgef_drains', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 3)
    CreateObject('rgef_drains', 3)
    CreateParticle('rgef02', 4)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 5)
    CreateObject('rgef_drains', 5)
    CreateParticle('rgef02', 6)
    CreateObject('rgef_drains', 6)
    CreateParticle('rgef02', 7)
    CreateObject('rgef_drains', 7)
    CreateParticle('rgef02', 8)
    CreateObject('rgef_drains', 8)
    CreateParticle('rgef02', 9)
    CreateObject('rgef_drains', 9)
    sprite('vrrgef440_05', 3)


@State
def rgef440Ex():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        PaletteIndex(1)
        IgnorePauses(2)
        AddX(500000)
        AddScale(400)
    sprite('vrrgef440_00', 6)
    ScreenShake(20000, 20000)
    sprite('vrrgef440_01', 5)
    sprite('vrrgef440_02', 4)
    sprite('vrrgef440_03', 3)
    sprite('vrrgef440_04', 3)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)
    CreateParticle('rgef02', 1)
    CreateObject('rgef_drains', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 3)
    CreateObject('rgef_drains', 3)
    CreateParticle('rgef02', 4)
    CreateObject('rgef_drains', 4)
    CreateParticle('rgef02', 5)
    CreateObject('rgef_drains', 5)
    CreateParticle('rgef02', 6)
    CreateObject('rgef_drains', 6)
    CreateParticle('rgef02', 7)
    CreateObject('rgef_drains', 7)
    CreateParticle('rgef02', 8)
    CreateObject('rgef_drains', 8)
    CreateParticle('rgef02', 9)
    CreateObject('rgef_drains', 9)
    sprite('vrrgef440_05', 3)


@State
def rgef440StartEff():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        PaletteIndex(1)
        AlphaValue(245)
        Size(1450)
        AddY(-25000)
        AddX(75000)
        RenderLayer(6)
    sprite('vrrgef440_10', 6)
    sprite('vrrgef440_11', 5)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    sprite('vrrgef440_12', 5)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef440_13', 5)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef440_14', 4)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)
    sprite('vrrgef440_15', 4)
    CreateParticle('rgef02', 0)
    CreateObject('rgef_drains', 0)


@State
def rgef450():

    def upon_IMMEDIATE():
        E0EAEffectPosition(2)
        RemoveOnCallStateEnd(2)
        SetZVal(-500)
        BlendMode_Add()
        AlphaValue(255)
    sprite('vrrgef450atk_00', 2)
    sprite('vrrgef450atk_01', 2)
    sprite('vrrgef450atk_02', 3)
    sprite('vrrgef450atk_03', 5)
    sprite('vrrgef450atk_04', 5)
    sprite('vrrgef450atk_05', 5)
    sprite('vrrgef450atk_06', 5)
    ConstantAlphaModifier(-10)


@State
def rgef451atk():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        IgnorePauses(3)
        EnableAfterimage(1)
        AfterimageCount(3)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AddX(100000)
        Size(1500)
    sprite('vrrgef451atk_01', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef451atk_02', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    sprite('vrrgef451atk_03', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    sprite('vrrgef451atk_04', 4)
    Size(750)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateParticle('rgef02', 10)
    CreateParticle('rgef02', 11)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    CreateObject('rgef_drain', 8)
    CreateObject('rgef_drain', 9)
    CreateObject('rgef_drain', 10)
    CreateObject('rgef_drain', 11)
    sprite('vrrgef451atk_05', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    E0EAEffectPosition(0)
    sprite('vrrgef451atk_06', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    sprite('vrrgef451atk_07', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef451atk_08', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    sprite('vrrgef451atk_09', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef451atk_10', 3)
    sprite('null', 12)


@State
def rgef451atkOD():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        IgnorePauses(3)
        EnableAfterimage(1)
        AfterimageCount(3)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        AddX(100000)
        Size(1500)
    sprite('vrrgef451atk_01', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    sprite('vrrgef451atk_02', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    sprite('vrrgef451atk_03', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateObject('rgef_drain', 5)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    sprite('vrrgef451atk_04', 2)
    Size(750)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateParticle('rgef02', 10)
    CreateParticle('rgef02', 11)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    CreateObject('rgef_drain', 8)
    CreateObject('rgef_drain', 9)
    CreateObject('rgef_drain', 10)
    CreateObject('rgef_drain', 11)
    sprite('vrrgef451atk_04', 2)
    AddScale(150)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateParticle('rgef02', 10)
    CreateParticle('rgef02', 11)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    CreateObject('rgef_drain', 8)
    CreateObject('rgef_drain', 9)
    CreateObject('rgef_drain', 10)
    CreateObject('rgef_drain', 11)
    sprite('vrrgef451atk_04', 2)
    AddScale(150)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateParticle('rgef02', 10)
    CreateParticle('rgef02', 11)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    CreateObject('rgef_drain', 8)
    CreateObject('rgef_drain', 9)
    CreateObject('rgef_drain', 10)
    CreateObject('rgef_drain', 11)
    sprite('vrrgef451atk_04', 2)
    AddScale(150)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateParticle('rgef02', 10)
    CreateParticle('rgef02', 11)
    CreateObject('rgef_drain', 6)
    CreateObject('rgef_drain', 7)
    CreateObject('rgef_drain', 8)
    CreateObject('rgef_drain', 9)
    CreateObject('rgef_drain', 10)
    CreateObject('rgef_drain', 11)
    sprite('vrrgef451atk_05', 4)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    E0EAEffectPosition(0)
    sprite('vrrgef451atk_06', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    CreateParticle('rgef02', 9)
    sprite('vrrgef451atk_07', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef451atk_08', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    sprite('vrrgef451atk_09', 3)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef451atk_10', 3)
    sprite('null', 12)


@State
def rgef610wingmake():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-100)
        BlendMode_Normal()
        AlphaValue(255)
    sprite('rgef610_02', 3)
    sprite('rgef610_03', 3)
    sprite('rgef610_04', 3)
    sprite('rgef610_05', 3)
    sprite('rgef610_06', 3)
    sprite('rgef610_06ex01', 3)


@State
def rgef610wingbreak():

    def upon_IMMEDIATE():
        PaletteIndex(1)
        E0EAEffectPosition(3)
        RemoveOnCallStateEnd(3)
        SetZVal(-100)
        EnableAfterimage(1)
        AfterimageInterval(1)
        AfterimageCount(4)
        AfterimageSize_1(1000)
        AfterimageSize_2(1000)
        BlendMode_Normal()
        AlphaValue(255)
    sprite('rgef610_07', 2)
    ConstantAlphaModifier(-5)
    SetScaleSpeedY(5)
    SetScaleXPerFrame(10)
    sprite('rgef610_08', 2)
    sprite('rgef610_09', 2)
    CreateParticle('rgef610', 4)
    CreateParticle('rgef610', 5)
    CreateParticle('rgef610', 6)
    CreateParticle('rgef610', 7)
    sprite('rgef610_10', 2)
    CreateParticle('rgef610', 0)
    CreateParticle('rgef610', 1)
    CreateParticle('rgef610', 2)
    CreateParticle('rgef610', 3)
    sprite('rgef610_11', 2)
    CreateParticle('rgef610', 0)
    CreateParticle('rgef610', 1)
    CreateParticle('rgef610', 2)
    CreateParticle('rgef610', 3)
    CreateParticle('rgef610', 4)
    CreateParticle('rgef610', 5)
    CreateParticle('rgef610', 6)
    CreateParticle('rgef610', 7)
    sprite('rgef610_12', 2)
    CreateParticle('rgef610', 0)
    CreateParticle('rgef610', 1)
    CreateParticle('rgef610', 2)
    CreateParticle('rgef610', 3)
    CreateParticle('rgef610', 4)
    CreateParticle('rgef610', 5)
    CreateParticle('rgef610', 6)
    CreateParticle('rgef610', 7)
    sprite('rgef610_13', 3)
    CreateParticle('rgef610', 0)
    CreateParticle('rgef610', 1)
    CreateParticle('rgef610', 2)
    CreateParticle('rgef610', 3)
    sprite('rgef610_14', 3)
    CreateParticle('rgef610', 4)
    CreateParticle('rgef610', 5)
    CreateParticle('rgef610', 6)
    CreateParticle('rgef610', 7)
    sprite('rgef610_15', 4)
    CreateParticle('rgef610', 1)
    CreateParticle('rgef610', 2)
    CreateParticle('rgef610', 3)
    CreateParticle('rgef610', 4)
    sprite('rgef610_16', 4)
    sprite('null', 30)


@State
def AstralMoveSword():

    def upon_IMMEDIATE():
        SetScaleX(-1000)
    sprite('rg460_swd00', 4)
    physicsYImpulse(-34000)
    sprite('rg460_swd01', 4)
    sprite('rg460_swd02', 4)
    physicsYImpulse(2000)


@State
def ChangeToDeathscythe():

    def upon_IMMEDIATE():
        PaletteIndex(0)
        E0EAEffectPosition(3)
        IgnorePauses(3)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageBlendMode(2)
        AfterimageInterval(1)
        AfterimageCount(3)
        AfterimageSize_1(1000)
        AfterimageSize_2(1050)
        BlendMode_Normal()
        AlphaValue(255)
        SetScaleX(-1000)
    sprite('rg460_kama00', 1)
    PrivateSE('rgse_05')
    sprite('rg460_kama00ex01', 2)
    sprite('rg460_kama00ex02', 2)
    sprite('rg460_kama00ex03', 2)
    sprite('rg460_kama00ex04', 2)
    sprite('rg460_kama00ex05', 2)
    CommonSE('105_guard_slash_2')
    PrivateSE('rgse_21')
    sprite('rg460_kama01', 14)
    sprite('rg460_kama02', 2)
    sprite('rg460_kama03', 2)
    sprite('rg460_kama04', 2)
    sprite('rg460_kama05', 2)
    sprite('rg460_kama06', 2)
    sprite('rg460_kama07', 2)
    PrivateSE('rgse_25')
    PrivateSE('rgse_25')
    sprite('rg460_kama07ex01', 2)
    sprite('rg460_kama07ex02', 2)
    sprite('rg460_kama07', 2)
    sprite('rg460_kama07ex01', 2)
    sprite('rg460_kama07ex02', 2)
    loopRest()


@State
def nyPhantom():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        Hitstop(6)
        AttackLevel_(4)
        AttackP1(80)
        Damage(700)
        PushbackX(18000)
        Blockstun(25)
        Hitstun(25)
        AirUntechableTime(27)
        PaletteIndex(2)
        SetZVal(-500)
        Flip()
        AlphaValue(0)
        BlendMode_Normal()
        AddX(-600000)
        AddY(10000)
        Size(1000)
    sprite('ny600_11', 6)
    ConstantAlphaModifier(10)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    AlphaValue(128)
    ConstantAlphaModifier(0)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    ConstantAlphaModifier(-2)
    physicsXImpulse(1000)
    sprite('ny600_12', 6)
    physicsXImpulse(400)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)
    sprite('ny600_11', 6)
    sprite('ny600_12', 6)
    sprite('ny600_13', 6)
    sprite('ny600_14', 6)


@State
def rgef203atkD3rd():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(4)
        Damage(1300)
        AttackP1(85)
        AttackP2(82)
        MoveAttributes(0, 1, 0, 0, 0)
        AirHitstunAnimation(11)
        GroundedHitstunAnimation(11)
        Stagger(60)
        Crumple(42)
        PushbackX(12000)
        AirPushbackY(-60000)
        AirPushbackX(12000)
        YImpulseBeforeWallbounce(0)
        AirUntechableTime(90)
        HardKnockdown(1)
        Lifesteal(100, 100)
        ChipPercentage(0)
        CancelIfPlayerHit(3)
        E0EAEffectPosition(3)
        GuardCrushOld(800)
        GuardCrush(1, 1)
        PaletteIndex(1)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        Size(1500)
        AlphaValue(212)
        AddX(-150000)
    sprite('vrrgef203atk_00', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    sprite('vrrgef203atk_01', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef203atk_02', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_03', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_04ex', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_05ex', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_06ex', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef203atk_07', 4)
    AlphaValue(212)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_08', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_09', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    sprite('vrrgef203atk_10', 4)
    CreateParticle('rgef02', 0)


@State
def EventEffectRGVsTB_Hakumen():
    sprite('ha041_03', 32767)
    PaletteIndex(7)
    ForceFaceSprite()
    Flip()
    AddX(-520000)
    loopRest()


@State
def NOISE():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        Eff3DEffect('ef_eventnoise.DIG', '')
        FaceSpawnLocation()
        RenderLayer(4)
        SetPosXByScreenPer(50)
        SetPosYByScreenPer(50)
    sprite('null', 60)
    loopRest()


@State
def rgef414atk():

    def upon_IMMEDIATE():
        NoAttackDuringAction(1)
        CancelIfPlayerHit(3)
        E0EAEffectPosition(3)
        PaletteIndex(1)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        Size(1000)
        AlphaValue(212)
        AddX(-50000)
    sprite('vrrgef203atk_00', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    sprite('vrrgef203atk_01', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef203atk_02', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_03', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_04ex', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_05ex', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_06ex', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef203atk_07', 4)
    AlphaValue(212)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_08', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_09', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    sprite('vrrgef203atk_10', 4)
    CreateParticle('rgef02', 0)


@State
def DS_Niku_Head():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(1)
        ProjectileLevel(0)
        MoveAttributes(1, 0, 0, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Niku_Body():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(1)
        ProjectileLevel(0)
        MoveAttributes(0, 1, 0, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Niku_Leg():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(1)
        ProjectileLevel(0)
        MoveAttributes(0, 0, 1, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Niku_Approach():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(1)
        ProjectileLevel(0)
        MoveAttributes(0, 0, 0, 1, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Niku_Throw():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(1)
        ProjectileLevel(0)
        MoveAttributes(0, 0, 0, 0, 1)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Shot_Head():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(0)
        ProjectileLevel(1)
        MoveAttributes(1, 0, 0, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Shot_Body():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(0)
        ProjectileLevel(1)
        MoveAttributes(0, 1, 0, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Shot_Leg():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(0)
        ProjectileLevel(1)
        MoveAttributes(0, 0, 1, 0, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Shot_Approach():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(0)
        ProjectileLevel(1)
        MoveAttributes(0, 0, 0, 1, 0)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def DS_Shot_Throw():

    def upon_IMMEDIATE():
        AttackDefaults_SpecialProjectile()
        AttackLevel_(0)
        Damage(10000)
        DefeatOpponentBehavior(1)
        StrikeProjectileLevel(0)
        ProjectileLevel(1)
        MoveAttributes(0, 0, 0, 0, 1)
        PaletteIndex(1)
        TeleportToObject(22)
    sprite('vrrgef408_shot03', 60)


@State
def Eventrgef_drains():
    sprite('null', 200)
    ParticleColorFromPalette(224, 224, 224)
    CallPrivateEffect('rgef_draina')
    Size(2000)
    Visibility(1)


@State
def Eventrgef_drains2():
    sprite('null', 6)
    AddY(200000)
    ParticleSize(1500)
    ParticleRotationAngle(90000)
    CallCustomizableParticle('rgef00', 0)
    ParticleRotationAngle(90000)
    CallCustomizableParticle('rgef02', 0)
    ParticleRotationAngle(90000)
    CallCustomizableParticle('rgef02', 1)
    ParticleSize(1500)
    ParticleRotationAngle(90000)
    CallCustomizableParticle('rgef00', 2)


@State
def Eventrgef_drains3():

    def upon_IMMEDIATE():
        pass
    sprite('null', 100)
    AddY(200000)
    ParticleSize(3000)
    CallCustomizableParticle('rgef_drainstart', 0)
    ParticleColorFromPalette(215, 215, 209)
    CallCustomizableParticle('rgef432break', 0)


@State
def HAKUMEN_NOUNAI():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        ScreenPosition(1)
        XPositionRelativeFacing(-640000)
        AbsoluteY(0)
        Size(20000)
        uponSendToLabel(32, 0)
    sprite('vr_screen_black', 30)
    AlphaValue(0)
    ConstantAlphaModifier(4)
    sprite('vr_screen_black', 32767)
    ConstantAlphaModifier(0)
    AlphaValue(120)
    label(0)
    sprite('vr_screen_black', 30)
    ConstantAlphaModifier(-4)
    sprite('vr_screen_black', 10)
    AlphaValue(0)
    ConstantAlphaModifier(0)


@State
def Eventrgef414atk():

    def upon_IMMEDIATE():
        NoAttackDuringAction(1)
        CancelIfPlayerHit(3)
        E0EAEffectPosition(3)
        PaletteIndex(1)
        SetZVal(-500)
        EnableAfterimage(1)
        AfterimageCount(2)
        AfterimageSize_1(1000)
        AfterimageSize_2(1100)
        Size(1000)
        AlphaValue(212)
        AddX(-50000)
    sprite('vrrgef203atk_00', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    sprite('vrrgef203atk_01', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 0)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    sprite('vrrgef203atk_02', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_03', 4)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_04ex', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_05ex', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    StartMultihit()
    sprite('vrrgef203atk_06ex', 2)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateObject('rgef_drain', 4)
    CreateParticle('rgef02', 6)
    CreateParticle('rgef02', 7)
    CreateParticle('rgef02', 8)
    sprite('vrrgef203atk_07', 4)
    AlphaValue(212)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateObject('rgef_drain', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    CreateParticle('rgef02', 6)
    sprite('vrrgef203atk_08', 3)
    CreateObject('rgef_drain', 0)
    CreateObject('rgef_drain', 1)
    CreateObject('rgef_drain', 2)
    CreateParticle('rgef02', 3)
    CreateParticle('rgef02', 4)
    CreateParticle('rgef02', 5)
    sprite('vrrgef203atk_09', 4)
    CreateObject('rgef_drains', 0)
    CreateObject('rgef_drains', 1)
    CreateObject('rgef_drains', 2)
    CreateParticle('rgef02', 1)
    CreateParticle('rgef02', 2)
    CreateParticle('rgef02', 3)
    sprite('vrrgef203atk_10', 4)
    CreateParticle('rgef02', 0)


@State
def Eventoffset():

    def upon_IMMEDIATE():
        XPositionRelativeFacingAbsolute(0)
        AbsoluteY(1000000)
        DeviationX(-100000, 100000)
    sprite('null', 4)
    CreateParticle('ef_offset', 0)
    CommonSE('108_attack_offset')
    ScreenShake(30000, 30000)


@State
def EventRC():

    def upon_IMMEDIATE():
        LoadSpritePalette(0)
        uponSendToLabel(32, 10)
        XPositionRelativeFacing(-340000)
        SetZVal(501)
    label(0)
    sprite('rc000_00', 7)
    sprite('rc000_01', 7)
    sprite('rc000_02', 7)
    sprite('rc000_03', 7)
    sprite('rc000_04', 7)
    sprite('rc000_05', 7)
    sprite('rc000_06', 7)
    sprite('rc000_07', 7)
    sprite('rc000_08', 7)
    loopRest()
    gotoLabel(0)
    label(10)
    sprite('rc033_00', 2)
    physicsXImpulse(-30000)
    physicsYImpulse(20800)
    setGravity(850)
    JumpEffects(3, 100)
    sprite('rc033_01', 2)
    sprite('rc033_02', 3)
    sprite('rc033_03', 3)
    sprite('rc033_04', 3)
    sprite('rc033_05', 3)
    sprite('rc033_02', 3)
    sprite('rc033_03', 3)
    sprite('rc033_04', 3)
    sprite('rc033_05', 3)


@State
def EventWhiteOut():

    def upon_IMMEDIATE():
        SetZVal(-1000)
        BlendMode_Add()
        AlphaValue(0)
        Size(20000)
    sprite('vr_white', 20)
    ConstantAlphaModifier(15)
    sprite('vr_white', 45)
    sprite('vr_white', 20)
    AlphaValue(200)
    ConstantAlphaModifier(-10)


@State
def Act2Event_Yure():
    label(0)
    sprite('null', 10)
    ScreenShake(3000, 3000)
    CommonSE('019_quake_0')
    loopRest()
    gotoLabel(0)


@State
def Noise():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        Eff3DEffect('ef_eventnoise.DIG', '')
        FaceSpawnLocation()
        SetPosXByScreenPer(50)
        SetPosYByScreenPer(50)
    sprite('null', 30)
    CommonSE('014_electric_ml')
    loopRest()


@State
def Noise_Long():

    def upon_IMMEDIATE():
        BlendMode_Normal()
        Eff3DEffect('ef_eventnoise.DIG', '')
        FaceSpawnLocation()
        SetPosXByScreenPer(50)
        SetPosYByScreenPer(50)
        SetActionMark(5)
        SLOT_58 = 10

        def upon_EVERY_FRAME():
            if SLOT_2:
                AddActionMark(-1)
                if SLOT_2 <= 0:
                    SLOT_58 = SLOT_58 + -1
                    Unknown61(0, 30, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0)
                    SLOT_2 = SLOT_0
                    CommonSE('014_electric_l')
            if SLOT_58 <= 0:
                clearUponHandler(EVERY_FRAME)

        def upon_32():
            clearUponHandler(EVERY_FRAME)
            clearUponHandler(32)
            sendToLabel(0)
    sprite('null', 32767)
    label(0)
    sprite('null', 1)
